
connect_four: system execution failed.
Following is the set of recorded exceptions:

******************************** Thread exception *****************************
In thread           Root thread            0x0 (thread id)
*******************************************************************************
-------------------------------------------------------------------------------
Class / Object      Routine                Nature of exception           Effect
-------------------------------------------------------------------------------
ARRAY2              item @2                valid_column:                
<0000000004000FA8>                         Precondition violated.        Fail
-------------------------------------------------------------------------------
APPLICATION         make @25                                            
<0000000004000588>                         Routine failure.              Fail
-------------------------------------------------------------------------------
APPLICATION         root's creation                                     
<0000000004000588>                         Routine failure.              Exit
-------------------------------------------------------------------------------
ARRAY2              item @4                index_small_enough:          
<0000000004000FA8>  (From ARRAY)           Runtime check violated.       Exit
-------------------------------------------------------------------------------
ARRAY2              item @4                                             
<0000000004000FA8>  (From ARRAY)           Routine failure.              Exit
-------------------------------------------------------------------------------
ARRAY2              item @3                                             
<0000000004000FA8>                         Routine failure.              Exit
-------------------------------------------------------------------------------
APPLICATION         make @25                                            
<0000000004000588>                         Routine failure.              Exit
-------------------------------------------------------------------------------
APPLICATION         root's creation                                     
<0000000004000588>                         Routine failure.              Exit
-------------------------------------------------------------------------------
